# Generated by Django 4.2.10 on 2024-02-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.CharField(default='365c4b63-0da8-4b74-bc25-a1bbec1a515f', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new',
            name='password',
            field=models.CharField(max_length=400),
        ),
    ]
