# Generated by Django 4.2.10 on 2024-02-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_new_id_alter_new_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='email',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.CharField(default='20dfd4ff-a447-478b-8072-0beae04f8b26', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
