# Generated by Django 4.2.10 on 2024-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_email_new_username_alter_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.CharField(default='95d00439-9dfb-4d4d-99cb-b79e38fa82d6', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='new',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
