# Generated by Django 4.2.10 on 2024-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_new_id_alter_new_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
