# Generated by Django 4.2.10 on 2024-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_stock_status_alter_stock_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='status',
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
